name: Sync Repository

on:
  workflow_dispatch:
  schedule:
    # 设置定时触发，这里是每天的 UTC 时间 0:00（可根据需要调整）
    - cron: '0 0 * * *'

jobs:
  Fork-Filter-list:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0

    - name: Set up Git identity
      run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

   
    - name: Pull Scripts from RuCu6/QuanX
      run: |
          git remote add upstream https://github.com/RuCu6/QuanX.git
          git fetch upstream main:temp
          git checkout temp -- Scripts
          git checkout main
          git branch -D temp

    - name: Push Scripts to Your Repository
      run: |
          git add Scripts
          git commit -m "Sync Scripts from RuCu6/QuanX"
          git push main Scripts/RuCu6
