name: Sync Repository

on:
  workflow_dispatch:
  schedule:
    # 设置定时触发，这里是每天的 UTC 时间 0:00（可根据需要调整）
    - cron: '0 0 * * *'

jobs:
  Fork-Filter-list:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0

    - name: Pull content from RuCu6/QuanX
      run: |
        git clone https://github.com/RuCu6/QuanX.git
        git pull upstream QuanX/Scripts

    - name: Push to your repository
      run: |
        git push origin HEAD:main-scripts
