name: Convert Remote Resources

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

    
jobs:
  convert-resources:
    runs-on: ubuntu-latest # 使用 Ubuntu 环境运行作业

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # 检出仓库

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # 安装 Node.js 14

      - name: Install Dependencies
        run: |
          npm install -g @open-wa/wa-automate # 安装自动化脚本的依赖
          npm install -g @open-wa/wa-automate-cli # 安装自动化脚本的 CLI 工具
          
          
      - name: Run Conversion Script
        run: |
         # 执行自动化脚本
          wa-automate-cli convert-remote-resources \
            --input-url "https://example.com/resource.js" \ # 输入远程资源的 URL
            --output-file "converted.js" # 输出文件的名称，可以根据需要自定义




      - name: Commit Changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add converted.js
          git commit -m "Convert remote resources"
          git push

