name: fork

on:
  workflow_dispatch:
  
jobs:
  Fork-Filter-list:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: SouthAlley/z
        path: z-repo

    - name: Download file to Surge
      run: |
        mkdir -p z-repo/x

        # 广告规则 
        curl -L -o z-repo/x/text.txt "https://raw.githubusercontent.com/SouthAlley/z/main/x/ts.list"



    - name: Edit rule/ad
      run: |
        cd z-repo/x
        for file in text.txt; do
          if [ -f "$file" ]; then
            # 修改, 为,
            sed -i 's/, /,/g' "$file"
            # 在非注释后添加PROXY
            awk '!/\/\/|#|,PROXY|,DIRECT|,REJECT|^ *$/ {print $0",REJECT"; next} {print}' "$file" > tmpfile
            mv tmpfile "$file"
          else
            echo "$file not found."
          fi
        done


    - name: Add and Commits
      run: |
        cd z-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add x/* 
          git commit -m "Update"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi
