name: 更新
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml
          
      - name: Run Python
        run: |
          python Scripts/ChinaIP.py
          python Scripts/ChinaASN.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update IP List

      - name: Cleanup Workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 2
