name: 更新
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v3
     - name: Setup Python
       uses: actions/setup-python@v4.7.1
       with:
          python-version: 3.12
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install requests lxml
          
     - name: Run Python
       run: |
         python Scripts/qqq.py
     - uses: stefanzweifel/git-auto-commit-action@v4
       with:
          commit_message: Update IP List

     - name: Cleanup Workflow
       uses: Mattraks/delete-workflow-runs@main
       with:
          retain_days: 1
          keep_minimum_runs: 2
