name: Process and Push Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Fetch Remote File
      run: |
        curl -o filename.conf https://raw.githubusercontent.com/zZPiglet/Task/master/UnblockURLinWeChat.conf
        
    - name: Run Scripts
      run: |
        node Rewrite-Parser.js
        node script-converter.js

    - name: Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update processed file"
        git push
